language: python
python:
  - "3.6"
install:
  - sudo apt-get install php
  - pip install -r requirements.txt


before_script:
  - seleniumbase install chromedriver
  - php -S localhost:8000 &

script:
  - coverage run unitTest.py
  - pytest endToEndTest.py --browser=chrome --start-page=http://localhost:8000
