language: python
python:
  - "3.6"
install:
  - sudo apt-get install php
  - pip install -r requirements.txt

# launch website so it can be tested
#before_script:
 # - seleniumbase install chromedriver
  #- php -S localhost:8000 &

# command to run tests
script:
  - coverage run unitTest.py
